SectionDevice."Headphones" {
	Comment "Headphones"

	Value {
		PlaybackPriority 200
		PlaybackPCM "hw:${CardId}"
		PlaybackMixerElem "Headphone"
		PlaybackVolume "Headphone Volume"
		JackControl "Headphone Jack"
	}
	EnableSequence [
		cset "name='Playback Digital Switch' on,on"
		cset "name='Mixer Out FilterL DACL Switch' on"
		cset "name='Mixer Out FilterR DACR Switch' on"
		cset "name='Headphone Jack Switch' on"
	]
	DisableSequence [
		cset "name='Headphone Jack Switch' off"
		cset "name='Mixer Out FilterL DACL Switch' off"
		cset "name='Mixer Out FilterR DACR Switch' off"
		cset "name='Playback Digital Switch' off,off"
	]
}

SectionDevice."Headset Mic" {
	Comment "Headset Microphone"

	Value {
		CapturePriority 200
		CapturePCM "hw:${CardId}"
		CaptureMixerElem "Mic"
		CaptureVolume "Mic Volume"
		JackControl "Headset Mic Jack"
	}
	EnableSequence [
		cset "name='Capture Digital Switch' on"
		cset "name='Mixin Switch' on"
		cset "name='Mixer In Mic Switch' on"
		cset "name='Headset Mic Switch' on"
		cset "name='Mic Switch' on"
	]
	DisableSequence [
		cset "name='Headset Mic Switch' off"
		cset "name='Mic Switch' off"
		cset "name='Mixin Switch' off"
	]
}
