SectionDevice."Speaker" {
	Comment "Built-in Speakers"

	Value {
		PlaybackPriority 100
		PlaybackPCM "hw:${CardId}"
	}
	EnableSequence [
		cset "name='DSP Volume' 536870912"
		cset "name='Left DAI Sel Mux' Left"
		cset "name='Right DAI Sel Mux' Right"
	]
	DisableSequence [
	]
}
